services:
  - type: web
    name: secure-file-sharing-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  - type: web
    name: secure-file-sharing-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production